Практическая работа №1. Быстров М.В.
rick-nice/andersen-js-course pull request #1
Opened 2019-06-07 06:26 UTC by rick-nice

2019-06-08 10:15 UTC, volvachev requested changes

2019-06-08 10:15 UTC, volvachev commented on src/array-practice/task1.js
> +const any = (arr, cb) => {
Эта реализация не подходит. Верни реализацию через some, и подумай как можно улучшить.

2019-06-08 10:15 UTC, volvachev commented on src/array-practice/task10.js
> +    if (next.isActive) acc += next.members;
Деструктуризация. Воспользуйся тернарным оператором.

2019-06-08 10:15 UTC, volvachev commented on src/array-practice/task3.js
> +  array.forEach((elem, index) => {
Подумай о более лучшем решение, возможно надо будет воспользоваться ещё каким нибудь методом.

2019-06-08 10:15 UTC, volvachev commented on src/array-practice/task5.js
> +      return 'Complete!';
Воспользуйся тернарным оператором. shift мутирует исходный массив, работай с копией.

2019-06-08 10:15 UTC, volvachev commented on src/array-practice/task7.js
> +const take = (array, num) => array.splice(0, num);
Splice сюда не подходит он мутирует исходный массив. Воспользуйся другим методом массива.

2019-06-08 10:15 UTC, volvachev commented on src/array-practice/task9.js
> +    if (next === value) acc.push(index);
Никогда не пиши if в одну строчку.

2019-06-08 10:15 UTC, volvachev commented on src/es-features/task3.js
> +export const task3New = arr => [...[1, 2], ...arr];
Лишний спрэд с массивом, сделай с одним спрэдом.

2019-06-08 10:15 UTC, volvachev commented on src/es-features/task4.js
> +    ['baz' + foo()]: 'new field',
temlpate string

2019-06-08 10:15 UTC, volvachev commented on src/es-features/task5.js
> +  const { name: objName, val: objValue } = obj;
Деструктурируй прямо в аргументах.

2019-06-09 18:07 UTC, rick-nice commented on src/array-practice/task3.js
> +  array.forEach((elem, index) => {
Ну есть еще 2 варианта: через reverse - но он мутирует, значит не подходит; и sort - он отсортирует и новый массив даст. Очевидно, sort лучше из этих 2 вариантов, но чем он лучше моего решения? Просто ради читаемости?  По ресурсам он, полагаю, больше скушает.

2019-06-09 18:08 UTC, rick-nice commented on src/array-practice/task3.js
> +  array.forEach((elem, index) => {
> Подумай о более лучшем решение, возможно надо будет воспользоваться ещё каким нибудь методом.

Ну есть еще 2 варианта: через reverse - но он мутирует, значит не подходит; и sort - он отсортирует и новый массив даст. Очевидно, sort лучше из этих 2 вариантов, но чем он лучше моего решения? Просто ради читаемости?  По ресурсам он, полагаю, больше скушает.

2019-06-12 16:02 UTC, volvachev requested changes

2019-06-12 16:02 UTC, volvachev commented on src/array-practice/task3.js
> +    .sort((a, b) => b - a)
sort мутирует массив. работай с копией.
для forEach мог просто callback передавать.

2019-07-08 07:30 UTC, merged